model: skipgram
network:
  window_size: 2
  hidden_size: 64
  max_norm: 1
policy:
  lr: 0.005
  batch_size: 5000
  accumulation: 2
  save_interval: 5
  epochs: 100
  early_stop: 3
load:
  path: null
save:
  path: saving/{data.set}/{model.model}-W{model.network.window_size}
